name: gatsby-ceiphr
static_sites:
  - build_command: gatsby build
    environment_slug: gatsby
    github:
      branch: master
      deploy_on_push: true
      repo: ceiphr/gatsby-ceiphr
    name: gatsby-ceiphr
