---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.zeit.co/v1/integrations/deploy/QmNwejSLh88SVxavkDaEsmWz9kzahncdkzRnENMsHy4aYM/01ComJsm7Q
sections:
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: content/assets
public_path: "/content/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_TELEMETRY_DISABLED=1
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
